version: '2'
services:
  api-comunipsum:
    container_name: 'api-comunipsum'
    build: "./"
    restart: always
    ports:
      - 8000:8000
    command: /bin/sh -c $APP_COMUNIPSUM_START
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    tty: true
    env_file: .env
    depends_on:
      - db-comunipsum
    links:
      - db-comunipsum:db.comunipsum.local

  db-comunipsum:
    image: mongo:latest
    container_name: 'db-comunipsum'
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - VIRTUAL_HOST:$DB_COMUNIPSUM_VIRTUAL_HOST
