version: '2'
services:
  api-comunipsum:
    container_name: 'api-comunipsum'
    build: "./"
    restart: always
    ports:
      - 8000:8000
      - 9229:9229
    command: /bin/sh -c "npm run debug"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    tty: true
    env_file: .env